'use strict';

module.exports = {
  name: 'Hurricane',
  version: 'L-2',
  rom: {
    u06: 'hurcnl_2.rom',
    u14: 'U14.PP',
    u15: 'U15.PP',
    u18: 'U18.PP',
  },
  switchMapping: [
    { id: 11, name: 'RIGHT FLIPPER' },
    { id: 12, name: 'LEFT FLIPPER' },
    { id: 13, name: 'CREDIT BUTTON' },
    { id: 14, name: 'PLUMB BOB TILT' },
    { id: 15, name: 'OUTHOLE' },
    { id: 16, name: 'TROUGH 1' },
    { id: 17, name: 'TROUGH 2' },
    { id: 18, name: 'TROUGH 3' },

    { id: 21, name: 'SLAM TILT' },
    { id: 22, name: 'COIN DOOR CLOSED' },
    { id: 23, name: 'TICKED OPTQ' },
    { id: 25, name: 'RIGHT SLING' },
    { id: 26, name: 'RIGHT RETURN' },
    { id: 27, name: 'RIGHT OUTLANE' },
    { id: 28, name: 'BALL SHOOTER' },

    { id: 31, name: 'FERRIS WHEEL' },
    { id: 33, name: 'L DROP 1' },
    { id: 34, name: 'L DROP 2' },
    { id: 35, name: 'L DROP 3' },
    { id: 36, name: 'LEFT SLING' },
    { id: 37, name: 'LEFT RETURN' },
    { id: 38, name: 'LEFT OUTLANE' },

    { id: 42, name: 'RIGHT STANDUP 1' },
    { id: 43, name: 'RIGHT STANDUP 2' },
    { id: 44, name: 'RIGHT STANDUP 3' },
    { id: 45, name: 'RIGHT STANDUP 4' },

    { id: 51, name: 'LEFT JET' },
    { id: 52, name: 'RIGHT JET' },
    { id: 53, name: 'BOTTOM JET' },
    { id: 55, name: 'DUNK THE DUMMY' },
    { id: 56, name: 'LEFT JUGGLER' },
    { id: 57, name: 'RIGHT JUGGLER' },

    { id: 61, name: 'HURRICANE ENTRY' },
    { id: 62, name: 'HURRICANE EXIT' },
    { id: 63, name: 'COMET ENTRY' },
    { id: 64, name: 'COMET EXIT' },
  ],
  solenoidMapping: [
    { id: 1, name: 'BACKBOX MOTOR' },
    { id: 2, name: 'LEFT BANK' },
    { id: 4, name: 'LEFT JUGGLER' },
    { id: 5, name: 'RIGHT JUGGLER' },
    { id: 6, name: 'FERRIS WHEELS' },
    { id: 7, name: 'KNOCKER' },
    { id: 9, name: 'OUTHOLE' },
    { id: 10, name: 'BALL RELEASE' },
    { id: 11, name: 'LEFT SLING' },
    { id: 12, name: 'RIGHT SLING' },
    { id: 13, name: 'LEFT JET' },
    { id: 14, name: 'RIGHT JET' },
    { id: 15, name: 'BOTTOM JET' },
  ],
  skipWmcRomCheck: true,
  initialise: {
    closedSwitches: [ 22 ],
    initialAction: [
      {
        delayMs: 1000,
        source: 'cabinetInput',
        value: 16
      }
    ],
  },
  playfield: {
    //size must be 200x400, lamp positions according to image
    image: 'playfield-hurricane.jpg',
    lamps: [
      [{ x: 82, y: 312, color: 'YELLOW' }],
      [{ x: 98, y: 312, color: 'YELLOW' }],
      [{ x: 74, y: 325, color: 'ORANGE' }],
      [{ x: 91, y: 322, color: 'RED' }],
      [{ x: 107, y: 325, color: 'ORANGE' }],
      [{ x: 91, y: 338, color: 'RED' }], // CLOWN MOUTH
      [{ x: 10, y: 288, color: 'ORANGE' }], //LEFT OUTLANE
      [{ x: 26, y: 288, color: 'ORANGE' }], // LEFT RETURN LANE

      [{ x: 77, y: 295, color: 'LBLUE' }],
      [{ x: 67, y: 285, color: 'LBLUE' }],
      [{ x: 59, y: 277, color: 'LBLUE' }],
      [{ x: 54, y: 269, color: 'LBLUE' }],
      [{ x: 45, y: 261, color: 'LBLUE' }],
      [{ x: 32, y: 220, color: 'GREEN' }],
      [{ x: 35, y: 208, color: 'GREEN' }],
      [{ x: 37, y: 197, color: 'GREEN' }],

      [{ x: 67, y: 265, color: 'WHITE' }],
      [{ x: 75, y: 272, color: 'WHITE' }],
      [{ x: 85, y: 276, color: 'WHITE' }],
      [{ x: 96, y: 276, color: 'WHITE' }],
      [{ x: 106, y: 272, color: 'WHITE' }],
      [{ x: 113, y: 265, color: 'WHITE' }], //#36,PALACE E
      [{ x: 170, y: 287, color: 'ORANGE' }], //RIGHT OUTLANE
      [{ x: 155, y: 287, color: 'ORANGE' }],

      [{ x: 121, y: 244, color: 'RED' }], //#41, SPECIAL
      [{ x: 124, y: 232, color: 'ORANGE' }],
      [{ x: 127, y: 221, color: 'WHITE' }],
      [{ x: 131, y: 209, color: 'YELLOW' }],
      [{ x: 134, y: 197, color: 'WHITE' }],
      [{ x: 154, y: 108, color: 'YELLOW' }],
      [{ x: 160, y: 99, color: 'YELLOW' }],
      [{ x: 167, y: 108, color: 'YELLOW' }],

      [{ x: 56, y: 167, color: 'GREEN' }],
      [{ x: 55, y: 150, color: 'GREEN' }],
      [{ x: 56, y: 133, color: 'WHITE' }], //MYSTERY
      [{ x: 62, y: 110, color: 'YELLOW' }], //JACKPOT
      [{ x: 90, y: 371, color: 'ORANGE' }], //#55, PLAY IT AGAIN
      [{ x: 31, y: 165, color: 'WHITE' }],
      [{ x: 60, y: 45, color: 'YELLOW' }], //#57, FERRIS WHEEL - UNKNOWN
      [{ x: 87, y: 184, color: 'WHITE' }],

      [{ x: 79, y: 154, color: 'GREEN' }], //#61
      [{ x: 92, y: 153, color: 'RED' }],
      [{ x: 77, y: 141, color: 'ORANGE' }], //#63
      [{ x: 91, y: 140, color: 'WHITE' }],
      [{ x: 86, y: 92, color: 'BLACK' }],
      [{ x: 127, y: 80, color: 'BLACK' }],
      [{ x: 116, y: 120, color: 'BLACK' }],
      [{ x: 109, y: 188, color: 'LBLUE' }],

      [{ x: 91, y: 247, color: 'YELLOW' }], //#71
      [{ x: 93, y: 233, color: 'YELLOW' }],
      [{ x: 95, y: 217, color: 'YELLOW' }],
      [{ x: 80, y: 214, color: 'WHITE' }],
      [{ x: 153, y: 231, color: 'GREEN' }],
      [{ x: 151, y: 219, color: 'GREEN' }],
      [{ x: 149, y: 207, color: 'GREEN' }],
      [{ x: 147, y: 195, color: 'GREEN' }],

      [{ x: 164, y: 57, color: 'WHITE' }], // #81
      [{ x: 164, y: 30, color: 'WHITE' }],
      [{ x: 189, y: 28, color: 'WHITE' }],
      [{ x: 185, y: 59, color: 'WHITE' }],
      [{ x: 155, y: 359, color: 'WHITE' }, { x: 31, y: 359, color: 'WHITE' }],
      [{ x: 11, y: 389, color: 'YELLOW' }],
      [{ x: 39, y: 298, color: 'YELLOW' }],
      [{ x: 139, y: 298, color: 'YELLOW' }],
    ],
    flashlamps: [
      { id: 17, x: 188, y: 211, }, { id: 17, x: 188, y: 247, },
      { id: 18, x: 166, y: 14, }, { id: 18, x: 189, y: 28, },
      { id: 19, x: 95, y: 216, },
      { id: 20, x: 88, y: 185, },
      { id: 21, x: 62, y: 111, },
      { id: 22, x: 19, y: 119, },
      { id: 23, x: 13, y: 12, }, { id: 23, x: 35, y: 48, },
      { id: 24, x: 36, y: 344, },
      { id: 25, x: 138, y: 344, },
      { id: 26, x: 95, y: 112, },
      { id: 27, x: 116, y: 151, },
      { id: 28, x: 9, y: 241, },
    ],
  },
  gameLogic: [
    { name: 'Initial State',
      switchDownTimeMs: 0,
      nextState: 'Drain',
      transitionTimeMs: 0,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Playfield State' },
    { name: 'Right Trough',
      switchDownTimeMs: 1,
      switchIdToTrigger: 16,
      solenoidIdToLeaveState: 10,
      nextState: 'Shooter',
      transitionTimeMs: 5 },
    { name: 'Center Trough',
      switchDownTimeMs: 1,
      switchIdToTrigger: 17,
      nextState: 'Right Trough',
      transitionTimeMs: 1,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Left Trough',
      switchDownTimeMs: 1,
      switchIdToTrigger: 18,
      nextState: 'Center Trough',
      transitionTimeMs: 1,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Outhole',
      switchDownTimeMs: 1,
      switchIdToTrigger: 15,
      solenoidIdToLeaveState: 9,
      nextState: 'Left Trough',
      transitionTimeMs: 5 },
    { name: 'Drain',
      switchDownTimeMs: 1,
      nextState: 'Outhole',
      transitionTimeMs: 0,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Shooter',
      switchDownTimeMs: 1,
      switchIdToTrigger: 28,
      nextState: 'Hurricane Ramp',
      transitionTimeMs: 2,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Hurricane Ramp',
      nextState: 'Playfield State',
      transitionTimeMs: 0,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'No Strength',
      switchDownTimeMs: 1,
      nextState: 'Shooter',
      transitionTimeMs: 3,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Right Outlane',
      switchDownTimeMs: 1,
      switchIdToTrigger: 27,
      nextState: 'Drain',
      transitionTimeMs: 15,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Left Outlane',
      switchDownTimeMs: 1,
      switchIdToTrigger: 38,
      nextState: 'Drain',
      transitionTimeMs: 15,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Right Inlane',
      switchDownTimeMs: 1,
      switchIdToTrigger: 26,
      nextState: 'Playfield State',
      transitionTimeMs: 5,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Left Inlane',
      switchDownTimeMs: 1,
      switchIdToTrigger: 37,
      nextState: 'Playfield State',
      transitionTimeMs: 5,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Left Slingshot',
      switchDownTimeMs: 1,
      switchIdToTrigger: 36,
      nextState: 'Playfield State',
      transitionTimeMs: 1,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Rt Slingshot',
      switchDownTimeMs: 1,
      switchIdToTrigger: 25,
      nextState: 'Playfield State',
      transitionTimeMs: 1,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Enter Hurricne',
      switchDownTimeMs: 1,
      switchIdToTrigger: 61,
      nextState: 'Hurricane Made',
      transitionTimeMs: 10,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Hurricane Made',
      switchDownTimeMs: 1,
      switchIdToTrigger: 62,
      nextState: 'In Ramp',
      transitionTimeMs: 5,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'In Ramp',
      switchDownTimeMs: 1,
      nextState: 'Left Inlane',
      transitionTimeMs: 20,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Enter Comet',
      switchDownTimeMs: 1,
      switchIdToTrigger: 63,
      nextState: 'Comet Made',
      transitionTimeMs: 7,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Comet Made',
      switchDownTimeMs: 1,
      switchIdToTrigger: 64,
      nextState: 'Habitrail',
      transitionTimeMs: 3,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Habitrail',
      switchDownTimeMs: 1,
      nextState: 'Right Inlane',
      transitionTimeMs: 6,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Ferris Wheel 1',
      switchDownTimeMs: 1,
      switchIdToTrigger: 31,
      nextState: 'Ferris Wheel 2',
      transitionTimeMs: 40,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Ferris Wheel 2',
      switchDownTimeMs: 1,
      nextState: 'In Ramp',
      transitionTimeMs: 40,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Left Juggler',
      switchDownTimeMs: 1,
      switchIdToTrigger: 56,
      solenoidIdToLeaveState: 4,
      nextState: 'Right Juggler',
      transitionTimeMs: 0 },
    { name: 'Right Juggler',
      switchDownTimeMs: 1,
      switchIdToTrigger: 57,
      solenoidIdToLeaveState: 5,
      nextState: 'Left Bumper',
      transitionTimeMs: 1 },
    { name: 'Left Bumper',
      switchDownTimeMs: 1,
      switchIdToTrigger: 51,
      nextState: 'Right Bumper',
      transitionTimeMs: 3,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Right Bumper',
      switchDownTimeMs: 1,
      switchIdToTrigger: 52,
      nextState: 'Bottom Bumper',
      transitionTimeMs: 3,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Bottom Bumper',
      switchDownTimeMs: 1,
      switchIdToTrigger: 53,
      nextState: 'Down F. Center',
      transitionTimeMs: 7,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Down F. Center',
      switchDownTimeMs: 1,
      nextState: 'Playfield State',
      transitionTimeMs: 5,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Down From Ramp',
      switchDownTimeMs: 1,
      switchIdToTrigger: 61,
      nextState: 'Playfield State',
      transitionTimeMs: 5,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Top Drop Tgt',
      switchDownTimeMs: 1,
      switchIdToTrigger: 33,
      nextState: 'Playfield State',
      transitionTimeMs: 3,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Mid Drop Tgt',
      switchDownTimeMs: 1,
      switchIdToTrigger: 34,
      nextState: 'Playfield State',
      transitionTimeMs: 3,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Bot Drop Tgt',
      switchDownTimeMs: 1,
      switchIdToTrigger: 35,
      nextState: 'Playfield State',
      transitionTimeMs: 3,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Left Bumper 2',
      switchDownTimeMs: 1,
      switchIdToTrigger: 51,
      nextState: 'Playfield State',
      transitionTimeMs: 2,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Bottom Bumper 2',
      switchDownTimeMs: 1,
      switchIdToTrigger: 53,
      nextState: 'Playfield State',
      transitionTimeMs: 2,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Right Bumper 2',
      switchDownTimeMs: 1,
      switchIdToTrigger: 52,
      nextState: 'Playfield State',
      transitionTimeMs: 2,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Cat Target 1',
      switchDownTimeMs: 1,
      switchIdToTrigger: 42,
      nextState: 'Playfield State',
      transitionTimeMs: 2,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Cat Target 2',
      switchDownTimeMs: 1,
      switchIdToTrigger: 43,
      nextState: 'Playfield State',
      transitionTimeMs: 2,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Cat Target 3',
      switchDownTimeMs: 1,
      switchIdToTrigger: 44,
      nextState: 'Playfield State',
      transitionTimeMs: 2,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Cat Target 4',
      switchDownTimeMs: 1,
      switchIdToTrigger: 45,
      nextState: 'Playfield State',
      transitionTimeMs: 2,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Dunk The Dummy',
      switchDownTimeMs: 1,
      switchIdToTrigger: 55,
      nextState: 'Playfield State',
      transitionTimeMs: 2,
      options: [ 'INSTANT_LEAVE_STATE' ] }
  ],
};
