'use strict';

module.exports = {
  name: 'Medieval Madness',
  version: 'L-8',
  rom: {
    u06: 'mm_109b.bin',
  },
  switchMapping: [
    { id: 11, name: 'LAUNCH BUTTON' },
    { id: 12, name: 'CATAPULT TARGET' },
    { id: 13, name: 'START BUTTON' },
    { id: 14, name: 'PLUMB BOB TILT' },
    { id: 15, name: 'L TROLL TARGET' },
    { id: 16, name: 'LEFT OUTLANE' },
    { id: 17, name: 'RIGHT RETURN' },
    { id: 18, name: 'SHOOTER LANE' },

    { id: 21, name: 'SLAM TILT' },
    { id: 22, name: 'COIN DOOR CLOSED' },
    { id: 25, name: 'R TROLL TARGET' },
    { id: 26, name: 'LEFT RETURN' },
    { id: 27, name: 'RIGHT OUTLANE' },
    { id: 28, name: 'RIGHT EJECT' },

    { id: 31, name: 'TROUGH EJECT' },
    { id: 32, name: 'TROUGH BALL 1' },
    { id: 33, name: 'TROUGH BALL 2' },
    { id: 34, name: 'TROUGH BALL 3' },
    { id: 35, name: 'TROUGH BALL 4' },
    { id: 36, name: 'LEFT POPPER' },
    { id: 37, name: 'CASTLE GATE' },
    { id: 38, name: 'CATAPULT' },

    { id: 41, name: 'MOAT ENTER' },
    { id: 44, name: 'CASTLE LOCK' },
    { id: 45, name: 'L TROLL (U/PLDF)' },
    { id: 46, name: 'R TROLL (U/PLDF)' },
    { id: 47, name: 'LEFT TOP LANE' },
    { id: 48, name: 'RIGHT TOP LANE' },

    { id: 51, name: 'LEFT SLINGSHOT' },
    { id: 52, name: 'RIGHT SLINGSHOT' },
    { id: 53, name: 'LEFT JET' },
    { id: 54, name: 'BOTTOM JET' },
    { id: 55, name: 'RIGHT JET' },
    { id: 56, name: 'DRAWBRIDGE UP' },
    { id: 57, name: 'DRAWBRIDGE DOWN' },
    { id: 58, name: 'TOWER EXIT' },

    { id: 61, name: 'L RAMP ENTER' },
    { id: 62, name: 'L RAMP EXIT' },
    { id: 63, name: 'R RAMP ENTER' },
    { id: 64, name: 'R RAMP EXIT' },
    { id: 65, name: 'LEFT LOOP LO' },
    { id: 66, name: 'LEFT LOOP HI' },
    { id: 67, name: 'RIGHT LOOP LO' },
    { id: 68, name: 'RIGHT LOOP HI' },

    { id: 71, name: 'RIGHT BANK TOP' },
    { id: 72, name: 'RIGHT BANK MID' },
    { id: 73, name: 'RIGHT BANK BOT' },
    { id: 74, name: 'L TROLL UP' },
    { id: 75, name: 'R TROLL UP' },
  ],
  fliptronicsMapping: [
    { id: 'F1', name: 'R FLIPPER EOS' },
    { id: 'F2', name: 'R FLIPPER BUTTON' },
    { id: 'F3', name: 'L FLIPPER EOS' },
    { id: 'F4', name: 'L FLIPPER BUTTON' },
    { id: 'F6', name: 'UR FLIPPER BUT' },
    { id: 'F8', name: 'UL FLIPPER BUT' },
  ],
  skipWmcRomCheck: true,
  features: [
    'securityPic',
  ],
  initialise: {
    closedSwitches: [
      22,
      //OPTO SWITCHES: 31, 32, 33, 34, 35, 36, 37, 41,
      31, 36, 37, 41,
      'F2', 'F4', 'F6', 'F8',
    ],
    initialAction: [
      {
        delayMs: 1000,
        source: 'cabinetInput',
        value: 16
      }
    ],
  },
  gameLogic: [
    { name: 'Initial State',
      switchDownTimeMs: 0,
      nextState: 'Trough 4',
      transitionTimeMs: 0,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Playfield State' },
    { name: 'Trough 4',
      switchDownTimeMs: 1,
      switchIdToTrigger: 35,
      nextState: 'Trough 3',
      transitionTimeMs: 1,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Trough 3',
      switchDownTimeMs: 1,
      switchIdToTrigger: 34,
      nextState: 'Trough 2',
      transitionTimeMs: 1,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Trough 2',
      switchDownTimeMs: 1,
      switchIdToTrigger: 33,
      nextState: 'Trough 1',
      transitionTimeMs: 1,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Trough 1',
      switchDownTimeMs: 1,
      switchIdToTrigger: 32,
      solenoidIdToLeaveState: 2,
      nextState: 'Trough Jam',
      transitionTimeMs: 1 },
    { name: 'Trough Jam',
      switchDownTimeMs: 1,
      switchIdToTrigger: 31,
      nextState: 'Shooter',
      transitionTimeMs: 1,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Drain',
      switchDownTimeMs: 1,
      nextState: 'Trough 4',
      transitionTimeMs: 0,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Shooter',
      switchDownTimeMs: 1,
      switchIdToTrigger: 18,
      solenoidIdToLeaveState: 1,
      nextState: 'Ball Lane',
      transitionTimeMs: 0 },
    { name: 'Ball Lane',
      switchDownTimeMs: 1,
      nextState: 'Top Left Lane',
      transitionTimeMs: 12,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Right Outlane',
      switchDownTimeMs: 1,
      switchIdToTrigger: 27,
      nextState: 'Drain',
      transitionTimeMs: 15,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Left Outlane',
      switchDownTimeMs: 1,
      switchIdToTrigger: 16,
      nextState: 'Drain',
      transitionTimeMs: 15,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Right Inlane',
      switchDownTimeMs: 1,
      switchIdToTrigger: 17,
      nextState: 'Playfield State',
      transitionTimeMs: 5,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Left Inlane',
      switchDownTimeMs: 1,
      switchIdToTrigger: 26,
      nextState: 'Playfield State',
      transitionTimeMs: 5,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Left Slingshot',
      switchDownTimeMs: 1,
      switchIdToTrigger: 51,
      nextState: 'Playfield State',
      transitionTimeMs: 1,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Rt Slingshot',
      switchDownTimeMs: 1,
      switchIdToTrigger: 52,
      nextState: 'Playfield State',
      transitionTimeMs: 1,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Left Bumper',
      switchDownTimeMs: 1,
      switchIdToTrigger: 53,
      nextState: 'Playfield State',
      transitionTimeMs: 1,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Right Bumper',
      switchDownTimeMs: 1,
      switchIdToTrigger: 55,
      nextState: 'Playfield State',
      transitionTimeMs: 1,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Bottom Bumper',
      switchDownTimeMs: 1,
      switchIdToTrigger: 54,
      nextState: 'Playfield State',
      transitionTimeMs: 1,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Enter L. Ramp',
      switchDownTimeMs: 1,
      switchIdToTrigger: 61,
      nextState: 'L. Ramp Made',
      transitionTimeMs: 7,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'L. Ramp Made',
      switchDownTimeMs: 1,
      switchIdToTrigger: 62,
      nextState: 'L. Habitrail',
      transitionTimeMs: 3,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'L. Habitrail',
      switchDownTimeMs: 1,
      nextState: 'Left Inlane',
      transitionTimeMs: 7,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Enter R. Ramp',
      switchDownTimeMs: 1,
      switchIdToTrigger: 63,
      nextState: 'R. Ramp Made',
      transitionTimeMs: 7,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'R. Ramp Made',
      switchDownTimeMs: 1,
      switchIdToTrigger: 64,
      nextState: 'R. Habitrail',
      transitionTimeMs: 3,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'R. Habitrail',
      switchDownTimeMs: 1,
      nextState: 'Right Inlane',
      transitionTimeMs: 5,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Damsel Tower',
      switchDownTimeMs: 10,
      switchIdToTrigger: 58,
      nextState: 'Damsel Tower 2',
      transitionTimeMs: 0,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Damsel Tower 2',
      nextState: 'Playfield State',
      transitionTimeMs: 0,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Enter L. Loop',
      switchDownTimeMs: 1,
      switchIdToTrigger: 65,
      nextState: 'L. Loop Sw #2',
      transitionTimeMs: 2,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'L. Loop Sw #2',
      switchDownTimeMs: 2,
      switchIdToTrigger: 66,
      nextState: 'Top Right Lane',
      transitionTimeMs: 4,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'R. Loop Sw #2',
      switchDownTimeMs: 1,
      switchIdToTrigger: 68,
      nextState: 'R. Loop Sw #1',
      transitionTimeMs: 2,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'R. Loop Sw #1',
      switchDownTimeMs: 1,
      switchIdToTrigger: 67,
      nextState: 'Playfield State',
      transitionTimeMs: 3,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Enter R. Loop',
      switchDownTimeMs: 1,
      switchIdToTrigger: 67,
      nextState: 'R. Loop Sw #3',
      transitionTimeMs: 2,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'R. Loop Sw #3',
      switchDownTimeMs: 2,
      switchIdToTrigger: 68,
      nextState: 'Top Left Lane',
      transitionTimeMs: 4,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'L. Loop Sw #3',
      switchDownTimeMs: 1,
      switchIdToTrigger: 66,
      nextState: 'L. Loop Sw #1',
      transitionTimeMs: 2,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'L. Loop Sw #1',
      switchDownTimeMs: 1,
      switchIdToTrigger: 65,
      nextState: 'Playfield State',
      transitionTimeMs: 3,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Top Left Lane',
      switchDownTimeMs: 1,
      switchIdToTrigger: 47,
      nextState: 'Left Bumper 2',
      transitionTimeMs: 5,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Left Bumper 2',
      switchDownTimeMs: 1,
      switchIdToTrigger: 53,
      nextState: 'Right Bumper 2',
      transitionTimeMs: 3,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Right Bumper 2',
      switchDownTimeMs: 1,
      switchIdToTrigger: 55,
      nextState: 'Bottom Bumper 2',
      transitionTimeMs: 3,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Bottom Bumper 2',
      switchDownTimeMs: 1,
      switchIdToTrigger: 54,
      nextState: 'Down F. Right',
      transitionTimeMs: 5,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Down F. Right',
      switchDownTimeMs: 1,
      switchIdToTrigger: 67,
      nextState: 'Playfield State',
      transitionTimeMs: 5,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Top Right Lane',
      switchDownTimeMs: 1,
      switchIdToTrigger: 48,
      nextState: 'Left Bumper 2',
      transitionTimeMs: 5,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Down From Left',
      switchDownTimeMs: 1,
      switchIdToTrigger: 65,
      nextState: 'Playfield State',
      transitionTimeMs: 5,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Merlin\'s Hole',
      switchDownTimeMs: 1,
      switchIdToTrigger: 28,
      solenoidIdToLeaveState: 9,
      nextState: 'Out From Hole',
      transitionTimeMs: 0 },
    { name: 'Out From Hole',
      switchDownTimeMs: 1,
      nextState: 'Down F. Right',
      transitionTimeMs: 5,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Catapult Tgt.',
      switchDownTimeMs: 1,
      switchIdToTrigger: 12,
      nextState: 'Catapult',
      transitionTimeMs: 4,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Catapult',
      switchDownTimeMs: 1,
      switchIdToTrigger: 38,
      solenoidIdToLeaveState: 8,
      nextState: 'Ball Fired',
      transitionTimeMs: 0 },
    { name: 'Ball Fired',
      switchDownTimeMs: 1,
      nextState: 'L. Ramp Made',
      transitionTimeMs: 3,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'R. Top Target',
      switchDownTimeMs: 1,
      switchIdToTrigger: 71,
      nextState: 'Playfield State',
      transitionTimeMs: 3,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'R. Mid Target',
      switchDownTimeMs: 1,
      switchIdToTrigger: 72,
      nextState: 'Playfield State',
      transitionTimeMs: 3,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'R. Bot Target',
      switchDownTimeMs: 1,
      switchIdToTrigger: 73,
      nextState: 'Playfield State',
      transitionTimeMs: 3,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Left Troll',
      nextState: 'Playfield State',
      transitionTimeMs: 0,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Left Troll 2',
      switchDownTimeMs: 1,
      switchIdToTrigger: 45,
      nextState: 'Playfield State',
      transitionTimeMs: 5,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Right Troll',
      nextState: 'Playfield State',
      transitionTimeMs: 0,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Right Troll 2',
      switchDownTimeMs: 1,
      switchIdToTrigger: 46,
      nextState: 'Playfield State',
      transitionTimeMs: 5,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Left Troll T.',
      switchDownTimeMs: 1,
      switchIdToTrigger: 15,
      nextState: 'Playfield State',
      transitionTimeMs: 3,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Right Troll T.',
      switchDownTimeMs: 1,
      switchIdToTrigger: 25,
      nextState: 'Playfield State',
      transitionTimeMs: 3,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Top Left Lane 2',
      switchDownTimeMs: 1,
      switchIdToTrigger: 47,
      nextState: 'Playfield State',
      transitionTimeMs: 3,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Top Right Lane 2',
      switchDownTimeMs: 1,
      switchIdToTrigger: 48,
      nextState: 'Playfield State',
      transitionTimeMs: 3,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Left Hole',
      switchDownTimeMs: 1,
      switchIdToTrigger: 36,
      solenoidIdToLeaveState: 3,
      nextState: 'Out From Hole 2',
      transitionTimeMs: 0 },
    { name: 'Out From Hole 2',
      switchDownTimeMs: 1,
      nextState: 'Down From Left',
      transitionTimeMs: 3,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Lock Lane',
      switchDownTimeMs: 1,
      nextState: 'Castle Lock',
      transitionTimeMs: 3,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Castle Lock',
      switchDownTimeMs: 1,
      switchIdToTrigger: 44,
      nextState: 'Left Hole',
      transitionTimeMs: 7,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: '',
      nextState: 'Playfield State',
      transitionTimeMs: 0,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Castle Moat',
      switchDownTimeMs: 1,
      switchIdToTrigger: 41,
      nextState: 'Left Hole',
      transitionTimeMs: 7,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Castle Hit',
      switchDownTimeMs: 1,
      switchIdToTrigger: 41,
      nextState: 'Castle Hit 2',
      transitionTimeMs: 1,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Castle Hit 2',
      switchDownTimeMs: 1,
      switchIdToTrigger: 37,
      nextState: 'Castle Hit 3',
      transitionTimeMs: 1,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Castle Hit 3',
      switchDownTimeMs: 1,
      switchIdToTrigger: 41,
      nextState: 'Playfield State',
      transitionTimeMs: 4,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Enter Castle',
      switchDownTimeMs: 1,
      switchIdToTrigger: 41,
      nextState: 'Enter Castle 2',
      transitionTimeMs: 1,
      options: [ 'INSTANT_LEAVE_STATE' ] },
    { name: 'Enter Castle 2',
      switchDownTimeMs: 1,
      switchIdToTrigger: 37,
      nextState: 'Castle Lock',
      transitionTimeMs: 4,
      options: [ 'INSTANT_LEAVE_STATE' ] }
  ],
};
