params ='use strict';
params ='use strict';

module.exports = {
  getGameTasks: function() {
    return gameTasks;
  }
};

let gameTasks = {};

add = function( taskNumber, description ) {
    gameTasks[ taskNumber ] = description;
}

add(0x02, "GAME START" );
add(0x03, "team VS team -- player animation" );
add(0x04, "CREDIT ADD" );
add(0x05, "startup" );
add(0x06, "GAME OVER" );
add(0x07, "Enter Initials (callout)" );
add(0x08, "Enter Initials (selection)" );
add(0x09, "GRAND CHAMPION Award Credits" );
add(0x0A, "MATCH sequence" );
add(0x0B, "MATCH MATCHED" );
add(0x0C, "CREDIT ADD" );
add(0x0D, "tilt-warning DANGER DANGER" );
add(0x0F, "TILT with running player" );
add(0x10, "TILT" );
add(0x11, "Shoot Again" );
add(0x13, "Press Enter for Test Report" );
add(0x14, "CREDITS 1/2 flash" );
add(0x15, "Locating Balls Please Wait" );
add(0x16, "Volume Adjust" );
add(0x17, "Start Button CREDITS 0 Insert Coins" );
add(0x18, "Open Coin Door to use buttons" );
add(0x1B, "???_1B" );
add(0x1C, "Coin Door is Open" );
add(0x1E, "once every 5 team choices at start -- PRESS SHOOT" );
add(0x1F, "Autoburn-in Error" );
add(0x20, "Flipper Buttons Pass Center Button Shoots" );
add(0x26, "animation BASKET" );
add(0x30, "FIELD GOAL" );
add(0x31, "x FREE THROWS" );
add(0x32, "INBOUND PASS Watch for Ball" );
add(0x33, "x HOOPS" );
add(0x34, "POWER POINTS" );
add(0x35, "IN THE PAINT IS LIT Shoot Right Loop" );
add(0x36, "IN THE PAINT IS LIT Shoot Left Loop" );
add(0x37, "IN THE PAINT" );
add(0x38, "animation FREE THROW" );
add(0x39, "BALLY logo" );
add(0x3A, "TIPOFF" );
add(0x3B, "Shoot Center Ramp for FASTBREAK" );
add(0x3C, "FASTBREAK" );
add(0x3D, "Shoot Left Ramp for SLAM DUNK" );
add(0x3E, "SLAM DUNK" );
add(0x3F, "Shoot Center Ramp for Alley Oop" );
add(0x40, "Alley Oop combo" );
add(0x41, "Flip those Flippers" );
add(0x42, "Hot Dog Mania" );
add(0x43, "Trivia Quiz" );
add(0x44, "Egyptian Soda" );
add(0x45, "Half court hoops" );
add(0x46, "Hook shot hoops" );
add(0x47, "Run & shoot Hoops" );
add(0x48, "Multiball Hoops" );
add(0x4a, "3 PT SHOT" );
add(0x4b, "3 PT SHOT" );
add(0x4c, "3 PT SHOT complete" );
add(0x4d, "3 PT SHOT ANIMATION" );
add(0x4e, "SHOOT" );
add(0x4f, "sHOot" );
add(0x50, "sHOot" );
add(0x51, "sHOot" );
add(0x52, "shoot" );
add(0x53, "ShootAround Multiball" );
add(0x54, "ShootAround Flashing Letters" );
add(0x55, "Field Goal" );
add(0x56, "Stadium Goodies complete" );
add(0x57, "Multiballs complete" );
add(0x58, "Field Goals complete" );
add(0x59, "Combinations complete" );
add(0x5A, "POWER HOOPS COMPLETE" );
add(0x5B, "x POINTS COMPLETE" );
add(0x5C, "TROPHY COMPLETE" );
add(0x5D, "animation PLANETS COMET 1 RING" );
add(0x5E, "animation PLANETS COMET 2 RINGS" );
add(0x5F, "animation PLANETS COMET 3 RINGS" );
add(0x60, "animation PLANETS COMET 4 RINGS" );
add(0x61, "RINGS COMPLETE" );
add(0x62, "EXTRA BALL IS LIT" );
add(0x63, "EXTRA BALL animation" );
add(0x64, "MILLION DOLLAR BASKET SHOT" );
add(0x65, "MILLION DOLLAR SKILLSHOT Shoot a Basket" );
add(0x66, "YOU WIN THE MILLION DOLLAR SKILLSHOT" );
add(0x67, "YOU MISSED" );
add(0x68, "PLAYER ONE <team> IS UP" );
add(0x69, "FIELD GOAL" );
add(0x6A, "HALF COURT HOOPS" );
add(0x6B, "TIME IS UP" );
add(0x6C, "FIELD GOAL" );
add(0x6D, "HOOKSHOT HOOPS" );
add(0x6E, "TIME IS UP" );
add(0x6F, "FIELD GOAL" );
add(0x70, "RAN AND SHOOT HOOPS shoot" );
add(0x71, "TIME IS UP" );
add(0x72, "MULTIBALL HOOPS" );
add(0x73, "MULTIBALL HOOPS shoot" );
add(0x74, "FIELD GOAL" );
add(0x75, "x HOOPS LOOPS" );
add(0x76, "TROPHY MULTIBALL" );
add(0x77, "image basket" );
add(0x78, "effect PLAYER FLASH highlight left" );
add(0x79, "effect PLAYER FLASH highlight right" );
add(0x7A, "TIME IS UP (2 line)" );
add(0x7B, "YOU LOSE" );
add(0x7C, "YOU WIN" );
add(0x7D, "11 Points" );
add(0x7E, "Shoot For" );
add(0x7F, "TIME IS UP" );
add(0x80, "3 POINTS" );
add(0x81, "???_x81" );
add(0x82, "TIME IS UP" );
add(0x83, "YOUR ANSWER IS CORRECT" );
add(0x84, "YOUR ANSWER IS WRONG" );
add(0x85, "long form trivia question" );
add(0x86, "3 POINTS" );
add(0x87, "???_87" );
add(0x88, "TIME IS UP" );
add(0x89, "GAME START" );
add(0x8A, "GAME START" );
add(0x8B, "WATCH FOR BALL" );
add(0x8C, "YOU ARE AN NBA TEAM CHAMPION" );
add(0x8D, "?DMD disappears?" );
add(0x8E, "MIDNIGHT MADNESS" );
add(0x8F, "CRASH! BOOM! MOO! BANG! DOHO!" );
add(0x90, "HOLD FLIPPER BUTTON TO CHANGE VOLUME" );
add(0x91, "animation JUMP BALL" );
add(0x92, "TEAM SELECTION (linked)" );
add(0x93, "TOURNAMENT MODE READY (press start now)" );
add(0x94, "TOURNAMENT PLAY " );
add(0x95, "TOURNAMENT MODE ACTIVATED" );
add(0x96, "FOUL SHOT press shoot button" );
add(0x97, "FOUL SHOT 1 POINT" );
add(0x98, "serial debug display" );
add(0x99, "Waiting for Link" );
add(0x9A, "INSERT COINS FOR LINKED PLAY" );
add(0x9B, "WAITING FOR OPPONENT (press both flipper button to cancel)" );
add(0x9C, "BEGIN QUARTER x" );
add(0x9D, "END OF QUARTER (linked play)" );
add(0x9E, "TIME EXTENDED (linked play)" );
add(0x9F, "SUDDEN DEATH (win by 2 points)" );
add(0xA0, "YOU WIN" );
