params ='use strict';

module.exports = {
  getWpcErrors: function() {
    return wpcErrors;
  }
};

let wpcErrors = {};

add = function( errorNumber, errorMessage ) {
    wpcErrors[ errorNumber ] = errorMessage;
}

add( 0x01, "User break requested by key press" );
add( 0x02, "Value specified for LOCKED_CMOS is not in table" );
add( 0x03, "6809 'reserved vector' processed" );
add( 0x04, "swi 3 executed" );
add( 0x05, "swi 2 executed" );
add( 0x06, "nmi ocurred" );
add( 0x07, "Process sleep with stack too large" );
add( 0x08, "Couldn't allocate block for large stack!" );
add( 0x09, "free_block called w/ Null pointer" );
add( 0x0a, "Process not on list expected" );
add( 0x0b, "Request to Free Ram Block failed" )
add( 0x0c, "Exec hook called utility requiring a process id." )
add( 0x0d, "String too long for printf_buffer" )
add( 0x0e, "Ill formatted % clause in printf string" )
add( 0x0f, "Coil queue full" )
add( 0x10, "Bad pound clause embedded in string." )
add( 0x11, "Message number passed is beyond table." )
add( 0x12, "Head or Tail of coil queue out of range" )
add( 0x13, "GI bit from bit generator is bad" )
add( 0x14, "Flash time of zero used." )
add( 0x15, "GI Number out of range." )
add( 0x16, "Number to lamp/flag twiddler out of range." )
add( 0x17, "Lamp table invalid, or not in prime real estate." )
add( 0x18, "Lamp string number specified is too high" )
add( 0x19, "End Bracket while NOT in lamp string if statement." )
add( 0x1a, "Lamp string operator out of range" )
add( 0x1b, "Lamp string range op got lamps in wrong order." )
add( 0x1c, "endif encountered before 'then' on if in lamp string." )
add( 0x1d, "Bad matrix specified on lamp operation" )
add( 0x1e, "get_switch_bit munged its parameters" )
add( 0x1f, "Switch number passed to switch primitive too high" )
add( 0x20, "Cksum init call to region that's not Prime" )
add( 0x21, "long_binary_to_bcd passed zero length" )
add( 0x22, "Hook (indicated by U, in apfixed) must be in prime." )
// add( 0x23, "Special solenoid handlers not in prime real estate" )
add( 0x23, "Score req. w/ player_up invalid, tilt, go, or diag." )
add( 0x24, "Product of local and global score multipliers > 255" )
add( 0x25, "Process that just slept wrote to 1st 8 bytes of ram." )
add( 0x26, "Bad score multiplier specified." )
add( 0x27, "Table item out of range (beyond end of table)" )
// add( 0x29, "Printf:  Bad character following backslash." )
add( 0x29, "Lamp routine called with lamp 0." )
add( 0x2b, "Pointer for Printf won't fit in 16 bits." )
add( 0x2c, "Field not in segment area" )
add( 0x2d, "Attempt to store bit for field, beyond last byte" )
add( 0x2e, "Invalid time stamp passed to clock_time_stamp" )
add( 0x2f, "Process with leff_number has no lamp block" )
add( 0x30, "Bits in LF_ and LEFL_ flags must be in same position." )
add( 0x31, "LEF_FLASH_BYTES not large enought for phys. flashers" )
add( 0x32, "Process has P_LEFF_NUMBER w/o valid PID" )
// add( 0x33, "Tried to allocate flasher zero for lamp effect." )
add( 0x33, "Lamp effect block freed (instead of sys_leff_exit)" )
add( 0x34, "User field request by proc w/o that field defined." )
add( 0x35, "Invalid software field number" )
// add( 0x37, "Background display effect header invalid." )
add( 0x37, "sys_deff_check called for background display effect." )
add( 0x39, "Player up number invalid" )
add( 0x3a, "Bad or Missing Master Scroll block" )
add( 0x3b, "Master block required for setup or scroll operation" )
add( 0x3c, "Cannot locate previously setup scroll chunk" )
add( 0x3d, "Period or Comma 1st char, or after # (use space)" )
add( 0x3e, "Display scroller running with no source type set." )
add( 0x3f, "No matrix bit set for lamp effect. (string specified)" )
add( 0x40, "Addl. lamps allocted to effect specified NEW matrix." )
add( 0x41, "Software field flags need justification bits" )
add( 0x42, "Bad segment area specified to sys_copy_fixed_field" )
add( 0x43, "Dissolve requested, but background deff wasn't running" )
add( 0x44, "Invalid scroll chunk pointer." )
add( 0x45, "Stackable effect has flag conflict (amode etc.)" )
add( 0x46, "Endball called from game over" )
add( 0x47, "Request for player area byte, out of range" )
add( 0x48, "Multiball device number invalid" )
// add( 0x49, "Too many multiball devices specified" )
add( 0x49, "Irq Tail hook not in prime real estate" )
add( 0x4b, "No processes available for ball serve" )
add( 0x4c, "Multiball device zero used." )
add( 0x4d, "Unmonitored locked hole had a switch closure." )
add( 0x4e, "Lock count on eject hole was higher than 1" )
add( 0x4f, "Call to trough handler for endball returned." )
add( 0x50, "Call to trough handler for ball serve returned." )
add( 0x51, "audit_complete called by invalid process id" )
add( 0x52, "Could not get process block for mulitball device kickout." )
add( 0x53, "Device type number invalid for multiball device." )
add( 0x54, "Ball serve condition w/ no balls in trough (you must kick one)" )
add( 0x55, "MULTI_ALL_BALL_CHECK called while auditing in progress" )
// add( 0x56, "Quick leff resource req. by non-leff process" )
add( 0x56, "Non-display effect called sys_deff_exit" )
add( 0x58, "Non-lamp effect called sys_leff_exit" )
add( 0x59, "Effect stack pointer invalid" )
// add( 0x5a, "Bad sound table entry, or too many sound table entries" )
add( 0x5a, "Bad sound script operator" )
// add( 0x5c, "Whirl_field passed an invalid quadrant number" )
add( 0x5c, "Cmos ram left unprotected (sys_lock_cmos forgotten)" )
add( 0x5e, "HSTD Table would not initialize (Check Default Table)" )
add( 0x5f, "HSTD entry requested out of range" )
add( 0x60, "Display field too small for get_let" )
add( 0x61, "Internal error in GET_LET processing" )
add( 0x62, "Higher priority deff stopped Enter your Initials." )
add( 0x63, "LARGEST_HSTD_TABLE value not large enough" )
add( 0x64, "def_status MUST HAVE DEF_EQMAY set." )
add( 0x65, "Could not allocate block for test mode" )
add( 0x66, "Audit formatting number invalid" )
// add( 0x67, "adj_name_it must specify TRUE in adj table" )
add( 0x67, "Process dispatcher got a non-process block to dispatch" )
add( 0x69, "Bad special help routine requested" )
add( 0x6a, "Process executed an RTS instruction (instead of die)" )
add( 0x6b, "Too many audits for TOTAL_AUDITS value specified." )
// add( 0x6c, "Test report lost phasing w/ help sequencer" )
add( 0x6c, "Too many adjustments for ADJ_TOTAL value" )
add( 0x6d, "Exec routine called sys_get_block." )
// add( 0x6f, "User menu descriptors out of order." )
add( 0x6f, "Copied string too long for process block." )
// add( 0x71, "Display Req. from display effect routine." )
add( 0x71, "Sleep called from EXEC routine." )
add( 0x72, "Switch hit reported on switch in non-scanned column." )
add( 0x73, "Invalid audit ram referenced." )
// add( 0x75, "Exec level routine locked up (Detected by IRQ)" )
add( 0x75, "ad_replay_start value is not within min/max range." )
add( 0x76, "Switch test could not get a ram block" )
add( 0x78, "Ram byte ticket_to_dispense got corrupted." )
// add( 0x79, "Units (not tens) added to score." )
add( 0x79, "Current process wrote beyond its stack" )
add( 0x7a, "Current process underflowed its stack" )
// add( 0x7b, "Current process underflowed its stack" )
add( 0x7b, "DMX page allocator failed" )
add( 0x7c, "Unsupported picture format found" )
add( 0x7e, "Vapor lock got a ball beyond the max. allowed" )
add( 0x7f, "Picture index is beyond end of picture table" )
//add( 0x7f, "Vapor lock called to remove w/ 0 balls present" )
add( 0x80, "Remove your coin switch dispatch flags (to coin_switch_handler)." )
