'use strict';

import test from 'ava';
import convert from '../../../utils/stateconvert/convert';
import t2 from '../../../utils/stateconvert/t2';
import hurricane from '../../../utils/stateconvert/hurricane';
import mm from '../../../utils/stateconvert/mm';

test('pinmame statconvert should convert t2', (t) => {
  const result = convert.convertState(t2);
  t.deepEqual(result, T2_STATE);
});

test('pinmame statconvert should convert hurricane', (t) => {
  const result = convert.convertState(hurricane);
  t.deepEqual(result, HURRICANE_STATE);
});

test('pinmame statconvert should convert mm', (t) => {
  const result = convert.convertState(mm);
  t.deepEqual(result, MM_STATE);
});

const MM_STATE = [
  { name: 'Initial State',
    switchDownTimeMs: 0,
    nextState: 'Trough 4',
    transitionTimeMs: 0,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Trough 4',
    switchDownTimeMs: 1,
    switchIdToTrigger: 35,
    nextState: 'Trough 3',
    transitionTimeMs: 1,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Trough 3',
    switchDownTimeMs: 1,
    switchIdToTrigger: 34,
    nextState: 'Trough 2',
    transitionTimeMs: 1,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Trough 2',
    switchDownTimeMs: 1,
    switchIdToTrigger: 33,
    nextState: 'Trough 1',
    transitionTimeMs: 1,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Trough 1',
    switchDownTimeMs: 1,
    switchIdToTrigger: 32,
    solenoidIdToLeaveState: 2,
    nextState: 'Trough Jam',
    transitionTimeMs: 1 },
  { name: 'Trough Jam',
    switchDownTimeMs: 1,
    switchIdToTrigger: 31,
    nextState: 'Shooter',
    transitionTimeMs: 1,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Drain',
    switchDownTimeMs: 1,
    nextState: 'Trough 4',
    transitionTimeMs: 0,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Shooter',
    switchDownTimeMs: 1,
    switchIdToTrigger: 18,
    solenoidIdToLeaveState: 1,
    nextState: 'Ball Lane',
    transitionTimeMs: 0 },
  { name: 'Ball Lane',
    switchDownTimeMs: 1,
    nextState: 'Top Left Lane',
    transitionTimeMs: 12,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Right Outlane',
    switchDownTimeMs: 1,
    switchIdToTrigger: 27,
    nextState: 'Drain',
    transitionTimeMs: 15,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Left Outlane',
    switchDownTimeMs: 1,
    switchIdToTrigger: 16,
    nextState: 'Drain',
    transitionTimeMs: 15,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Right Inlane',
    switchDownTimeMs: 1,
    switchIdToTrigger: 17,
    nextState: 'stFree',
    transitionTimeMs: 5,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Left Inlane',
    switchDownTimeMs: 1,
    switchIdToTrigger: 26,
    nextState: 'stFree',
    transitionTimeMs: 5,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Left Slingshot',
    switchDownTimeMs: 1,
    switchIdToTrigger: 51,
    nextState: 'stFree',
    transitionTimeMs: 1,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Rt Slingshot',
    switchDownTimeMs: 1,
    switchIdToTrigger: 52,
    nextState: 'stFree',
    transitionTimeMs: 1,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Left Bumper',
    switchDownTimeMs: 1,
    switchIdToTrigger: 53,
    nextState: 'stFree',
    transitionTimeMs: 1,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Right Bumper',
    switchDownTimeMs: 1,
    switchIdToTrigger: 55,
    nextState: 'stFree',
    transitionTimeMs: 1,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Bottom Bumper',
    switchDownTimeMs: 1,
    switchIdToTrigger: 54,
    nextState: 'stFree',
    transitionTimeMs: 1,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Enter L. Ramp',
    switchDownTimeMs: 1,
    switchIdToTrigger: 61,
    nextState: 'L. Ramp Made',
    transitionTimeMs: 7,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'L. Ramp Made',
    switchDownTimeMs: 1,
    switchIdToTrigger: 62,
    nextState: 'L. Habitrail',
    transitionTimeMs: 3,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'L. Habitrail',
    switchDownTimeMs: 1,
    nextState: 'Left Inlane',
    transitionTimeMs: 7,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Enter R. Ramp',
    switchDownTimeMs: 1,
    switchIdToTrigger: 63,
    nextState: 'R. Ramp Made',
    transitionTimeMs: 7,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'R. Ramp Made',
    switchDownTimeMs: 1,
    switchIdToTrigger: 64,
    nextState: 'R. Habitrail',
    transitionTimeMs: 3,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'R. Habitrail',
    switchDownTimeMs: 1,
    nextState: 'Right Inlane',
    transitionTimeMs: 5,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Damsel Tower',
    switchDownTimeMs: 10,
    switchIdToTrigger: 58,
    nextState: 'Damsel Tower 2',
    transitionTimeMs: 0,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Enter L. Loop',
    switchDownTimeMs: 1,
    switchIdToTrigger: 65,
    nextState: 'L. Loop Sw #2',
    transitionTimeMs: 2,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'L. Loop Sw #2',
    switchDownTimeMs: 2,
    switchIdToTrigger: 66,
    nextState: 'Top Right Lane',
    transitionTimeMs: 4,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'R. Loop Sw #2',
    switchDownTimeMs: 1,
    switchIdToTrigger: 68,
    nextState: 'R. Loop Sw #1',
    transitionTimeMs: 2,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'R. Loop Sw #1',
    switchDownTimeMs: 1,
    switchIdToTrigger: 67,
    nextState: 'stFree',
    transitionTimeMs: 3,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Enter R. Loop',
    switchDownTimeMs: 1,
    switchIdToTrigger: 67,
    nextState: 'R. Loop Sw #3',
    transitionTimeMs: 2,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'R. Loop Sw #3',
    switchDownTimeMs: 2,
    switchIdToTrigger: 68,
    nextState: 'Top Left Lane',
    transitionTimeMs: 4,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'L. Loop Sw #3',
    switchDownTimeMs: 1,
    switchIdToTrigger: 66,
    nextState: 'L. Loop Sw #1',
    transitionTimeMs: 2,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'L. Loop Sw #1',
    switchDownTimeMs: 1,
    switchIdToTrigger: 65,
    nextState: 'stFree',
    transitionTimeMs: 3,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Top Left Lane',
    switchDownTimeMs: 1,
    switchIdToTrigger: 47,
    nextState: 'Left Bumper 2',
    transitionTimeMs: 5,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Left Bumper 2',
    switchDownTimeMs: 1,
    switchIdToTrigger: 53,
    nextState: 'Right Bumper 2',
    transitionTimeMs: 3,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Right Bumper 2',
    switchDownTimeMs: 1,
    switchIdToTrigger: 55,
    nextState: 'Bottom Bumper 2',
    transitionTimeMs: 3,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Bottom Bumper 2',
    switchDownTimeMs: 1,
    switchIdToTrigger: 54,
    nextState: 'Down F. Right',
    transitionTimeMs: 5,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Down F. Right',
    switchDownTimeMs: 1,
    switchIdToTrigger: 67,
    nextState: 'stFree',
    transitionTimeMs: 5,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Top Right Lane',
    switchDownTimeMs: 1,
    switchIdToTrigger: 48,
    nextState: 'Left Bumper 2',
    transitionTimeMs: 5,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Down From Left',
    switchDownTimeMs: 1,
    switchIdToTrigger: 65,
    nextState: 'stFree',
    transitionTimeMs: 5,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Merlin\'s Hole',
    switchDownTimeMs: 1,
    switchIdToTrigger: 28,
    solenoidIdToLeaveState: 9,
    nextState: 'Out From Hole',
    transitionTimeMs: 0 },
  { name: 'Out From Hole',
    switchDownTimeMs: 1,
    nextState: 'Down F. Right',
    transitionTimeMs: 5,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Catapult Tgt.',
    switchDownTimeMs: 1,
    switchIdToTrigger: 12,
    nextState: 'Catapult',
    transitionTimeMs: 4,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Catapult',
    switchDownTimeMs: 1,
    switchIdToTrigger: 38,
    solenoidIdToLeaveState: 8,
    nextState: 'Ball Fired',
    transitionTimeMs: 0 },
  { name: 'Ball Fired',
    switchDownTimeMs: 1,
    nextState: 'L. Ramp Made',
    transitionTimeMs: 3,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'R. Top Target',
    switchDownTimeMs: 1,
    switchIdToTrigger: 71,
    nextState: 'stFree',
    transitionTimeMs: 3,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'R. Mid Target',
    switchDownTimeMs: 1,
    switchIdToTrigger: 72,
    nextState: 'stFree',
    transitionTimeMs: 3,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'R. Bot Target',
    switchDownTimeMs: 1,
    switchIdToTrigger: 73,
    nextState: 'stFree',
    transitionTimeMs: 3,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Left Troll 2',
    switchDownTimeMs: 1,
    switchIdToTrigger: 45,
    nextState: 'stFree',
    transitionTimeMs: 5,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Right Troll 2',
    switchDownTimeMs: 1,
    switchIdToTrigger: 46,
    nextState: 'stFree',
    transitionTimeMs: 5,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Left Troll T.',
    switchDownTimeMs: 1,
    switchIdToTrigger: 15,
    nextState: 'stFree',
    transitionTimeMs: 3,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Right Troll T.',
    switchDownTimeMs: 1,
    switchIdToTrigger: 25,
    nextState: 'stFree',
    transitionTimeMs: 3,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Top Left Lane 2',
    switchDownTimeMs: 1,
    switchIdToTrigger: 47,
    nextState: 'stFree',
    transitionTimeMs: 3,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Top Right Lane 2',
    switchDownTimeMs: 1,
    switchIdToTrigger: 48,
    nextState: 'stFree',
    transitionTimeMs: 3,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Left Hole',
    switchDownTimeMs: 1,
    switchIdToTrigger: 36,
    solenoidIdToLeaveState: 3,
    nextState: 'Out From Hole 2',
    transitionTimeMs: 0 },
  { name: 'Out From Hole 2',
    switchDownTimeMs: 1,
    nextState: 'Down From Left',
    transitionTimeMs: 3,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Lock Lane',
    switchDownTimeMs: 1,
    nextState: 'Castle Lock',
    transitionTimeMs: 3,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Castle Lock',
    switchDownTimeMs: 1,
    switchIdToTrigger: 44,
    nextState: 'Left Hole',
    transitionTimeMs: 7,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Castle Moat',
    switchDownTimeMs: 1,
    switchIdToTrigger: 41,
    nextState: 'Left Hole',
    transitionTimeMs: 7,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Castle Hit',
    switchDownTimeMs: 1,
    switchIdToTrigger: 41,
    nextState: 'Castle Hit 2',
    transitionTimeMs: 1,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Castle Hit 2',
    switchDownTimeMs: 1,
    switchIdToTrigger: 37,
    nextState: 'Castle Hit 3',
    transitionTimeMs: 1,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Castle Hit 3',
    switchDownTimeMs: 1,
    switchIdToTrigger: 41,
    nextState: 'stFree',
    transitionTimeMs: 4,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Enter Castle',
    switchDownTimeMs: 1,
    switchIdToTrigger: 41,
    nextState: 'Enter Castle 2',
    transitionTimeMs: 1,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Enter Castle 2',
    switchDownTimeMs: 1,
    switchIdToTrigger: 37,
    nextState: 'Castle Lock',
    transitionTimeMs: 4,
    options: [ 'INSTANT_LEAVE_STATE' ] }
];

const HURRICANE_STATE = [
  { name: 'Initial State',
    switchDownTimeMs: 0,
    nextState: 'Right Trough',
    transitionTimeMs: 0,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Right Trough',
    switchDownTimeMs: 1,
    switchIdToTrigger: 16,
    solenoidIdToLeaveState: 10,
    nextState: 'Shooter',
    transitionTimeMs: 5 },
  { name: 'Center Trough',
    switchDownTimeMs: 1,
    switchIdToTrigger: 17,
    nextState: 'Right Trough',
    transitionTimeMs: 1,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Left Trough',
    switchDownTimeMs: 1,
    switchIdToTrigger: 18,
    nextState: 'Center Trough',
    transitionTimeMs: 1,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Outhole',
    switchDownTimeMs: 1,
    switchIdToTrigger: 15,
    solenoidIdToLeaveState: 9,
    nextState: 'Left Trough',
    transitionTimeMs: 5 },
  { name: 'Drain',
    switchDownTimeMs: 1,
    nextState: 'Outhole',
    transitionTimeMs: 0,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Shooter',
    switchDownTimeMs: 1,
    switchIdToTrigger: 28,
    nextState: 'Hurricane Ramp',
    transitionTimeMs: 2,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'No Strength',
    switchDownTimeMs: 1,
    nextState: 'Shooter',
    transitionTimeMs: 3,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Right Outlane',
    switchDownTimeMs: 1,
    switchIdToTrigger: 27,
    nextState: 'Drain',
    transitionTimeMs: 15,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Left Outlane',
    switchDownTimeMs: 1,
    switchIdToTrigger: 38,
    nextState: 'Drain',
    transitionTimeMs: 15,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Right Inlane',
    switchDownTimeMs: 1,
    switchIdToTrigger: 26,
    nextState: 'stFree',
    transitionTimeMs: 5,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Left Inlane',
    switchDownTimeMs: 1,
    switchIdToTrigger: 37,
    nextState: 'stFree',
    transitionTimeMs: 5,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Left Slingshot',
    switchDownTimeMs: 1,
    switchIdToTrigger: 36,
    nextState: 'stFree',
    transitionTimeMs: 1,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Rt Slingshot',
    switchDownTimeMs: 1,
    switchIdToTrigger: 25,
    nextState: 'stFree',
    transitionTimeMs: 1,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Enter Hurricne',
    switchDownTimeMs: 1,
    switchIdToTrigger: 61,
    nextState: 'Hurricane Made',
    transitionTimeMs: 10,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Hurricane Made',
    switchDownTimeMs: 1,
    switchIdToTrigger: 62,
    nextState: 'In Ramp',
    transitionTimeMs: 5,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'In Ramp',
    switchDownTimeMs: 1,
    nextState: 'Left Inlane',
    transitionTimeMs: 20,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Enter Comet',
    switchDownTimeMs: 1,
    switchIdToTrigger: 63,
    nextState: 'Comet Made',
    transitionTimeMs: 7,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Comet Made',
    switchDownTimeMs: 1,
    switchIdToTrigger: 64,
    nextState: 'Habitrail',
    transitionTimeMs: 3,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Habitrail',
    switchDownTimeMs: 1,
    nextState: 'Right Inlane',
    transitionTimeMs: 6,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Ferris Wheel 1',
    switchDownTimeMs: 1,
    switchIdToTrigger: 31,
    nextState: 'Ferris Wheel 2',
    transitionTimeMs: 40,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Ferris Wheel 2',
    switchDownTimeMs: 1,
    nextState: 'In Ramp',
    transitionTimeMs: 40,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Left Juggler',
    switchDownTimeMs: 1,
    switchIdToTrigger: 56,
    solenoidIdToLeaveState: 4,
    nextState: 'Right Juggler',
    transitionTimeMs: 0 },
  { name: 'Right Juggler',
    switchDownTimeMs: 1,
    switchIdToTrigger: 57,
    solenoidIdToLeaveState: 5,
    nextState: 'Left Bumper',
    transitionTimeMs: 1 },
  { name: 'Left Bumper',
    switchDownTimeMs: 1,
    switchIdToTrigger: 51,
    nextState: 'Right Bumper',
    transitionTimeMs: 3,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Right Bumper',
    switchDownTimeMs: 1,
    switchIdToTrigger: 52,
    nextState: 'Bottom Bumper',
    transitionTimeMs: 3,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Bottom Bumper',
    switchDownTimeMs: 1,
    switchIdToTrigger: 53,
    nextState: 'Down F. Center',
    transitionTimeMs: 7,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Down F. Center',
    switchDownTimeMs: 1,
    nextState: 'stFree',
    transitionTimeMs: 5,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Down From Ramp',
    switchDownTimeMs: 1,
    switchIdToTrigger: 61,
    nextState: 'stFree',
    transitionTimeMs: 5,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Top Drop Tgt',
    switchDownTimeMs: 1,
    switchIdToTrigger: 33,
    nextState: 'stFree',
    transitionTimeMs: 3,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Mid Drop Tgt',
    switchDownTimeMs: 1,
    switchIdToTrigger: 34,
    nextState: 'stFree',
    transitionTimeMs: 3,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Bot Drop Tgt',
    switchDownTimeMs: 1,
    switchIdToTrigger: 35,
    nextState: 'stFree',
    transitionTimeMs: 3,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Left Bumper 2',
    switchDownTimeMs: 1,
    switchIdToTrigger: 51,
    nextState: 'stFree',
    transitionTimeMs: 2,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Bottom Bumper 2',
    switchDownTimeMs: 1,
    switchIdToTrigger: 53,
    nextState: 'stFree',
    transitionTimeMs: 2,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Right Bumper 2',
    switchDownTimeMs: 1,
    switchIdToTrigger: 52,
    nextState: 'stFree',
    transitionTimeMs: 2,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Cat Target 1',
    switchDownTimeMs: 1,
    switchIdToTrigger: 42,
    nextState: 'stFree',
    transitionTimeMs: 2,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Cat Target 2',
    switchDownTimeMs: 1,
    switchIdToTrigger: 43,
    nextState: 'stFree',
    transitionTimeMs: 2,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Cat Target 3',
    switchDownTimeMs: 1,
    switchIdToTrigger: 44,
    nextState: 'stFree',
    transitionTimeMs: 2,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Cat Target 4',
    switchDownTimeMs: 1,
    switchIdToTrigger: 45,
    nextState: 'stFree',
    transitionTimeMs: 2,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Dunk The Dummy',
    switchDownTimeMs: 1,
    switchIdToTrigger: 55,
    nextState: 'stFree',
    transitionTimeMs: 2,
    options: [ 'INSTANT_LEAVE_STATE' ] }
];

const T2_STATE = [
  { name: 'Initial State',
    switchDownTimeMs: 0,
    nextState: 'Right Trough',
    transitionTimeMs: 0,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Right Trough',
    switchDownTimeMs: 1,
    switchIdToTrigger: 17,
    solenoidIdToLeaveState: 4,
    nextState: 'Shooter',
    transitionTimeMs: 5 },
  { name: 'Center Trough',
    switchDownTimeMs: 1,
    switchIdToTrigger: 16,
    nextState: 'Right Trough',
    transitionTimeMs: 1,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Left Trough',
    switchDownTimeMs: 1,
    switchIdToTrigger: 15,
    nextState: 'Center Trough',
    transitionTimeMs: 1,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Outhole',
    switchDownTimeMs: 5,
    switchIdToTrigger: 18,
    solenoidIdToLeaveState: 3,
    nextState: 'Left Trough',
    transitionTimeMs: 5 },
  { name: 'Drain',
    switchDownTimeMs: 1,
    nextState: 'Outhole',
    transitionTimeMs: 0,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Shooter',
    switchDownTimeMs: 1,
    switchIdToTrigger: 78,
    solenoidIdToLeaveState: 9,
    nextState: 'Ball Lane',
    transitionTimeMs: 1 },
  { name: 'Ball Lane',
    switchDownTimeMs: 1,
    nextState: 'Orbit Target 2',
    transitionTimeMs: 5,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Right Outlane',
    switchDownTimeMs: 1,
    switchIdToTrigger: 28,
    nextState: 'Drain',
    transitionTimeMs: 20,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Left Outlane',
    switchDownTimeMs: 1,
    switchIdToTrigger: 25,
    nextState: 'Drain',
    transitionTimeMs: 20,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Right Inlane',
    switchDownTimeMs: 1,
    switchIdToTrigger: 27,
    nextState: 'stFree',
    transitionTimeMs: 5,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Left  Inlane',
    switchDownTimeMs: 1,
    switchIdToTrigger: 26,
    nextState: 'stFree',
    transitionTimeMs: 5,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Left Loop Up',
    switchDownTimeMs: 1,
    switchIdToTrigger: 53,
    nextState: 'Left Loop Up2',
    transitionTimeMs: 1,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Left Loop Up2',
    switchDownTimeMs: 1,
    switchIdToTrigger: 54,
    nextState: 'Top Lock',
    transitionTimeMs: 15,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Top Lock',
    switchDownTimeMs: 5,
    switchIdToTrigger: 55,
    solenoidIdToLeaveState: 10,
    nextState: 'Left Rollover',
    transitionTimeMs: 25 },
  { name: 'Left Loop Down',
    switchDownTimeMs: 1,
    switchIdToTrigger: 53,
    nextState: 'stFree',
    transitionTimeMs: 1,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Left Loop Down2',
    switchDownTimeMs: 1,
    switchIdToTrigger: 54,
    nextState: 'Left Loop Down',
    transitionTimeMs: 1,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Right Loop Up',
    switchDownTimeMs: 1,
    switchIdToTrigger: 65,
    nextState: 'Right Loop Up2',
    transitionTimeMs: 1,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Right Loop Up2',
    switchDownTimeMs: 1,
    switchIdToTrigger: 66,
    nextState: 'Left Loop Down2',
    transitionTimeMs: 10,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Right Loop Down',
    switchDownTimeMs: 1,
    switchIdToTrigger: 65,
    nextState: 'stFree',
    transitionTimeMs: 1,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Right Loop Down2',
    switchDownTimeMs: 1,
    switchIdToTrigger: 66,
    nextState: 'Right Loop Down',
    transitionTimeMs: 10,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'L. Ramp Enter',
    switchDownTimeMs: 1,
    switchIdToTrigger: 61,
    nextState: 'L. Ramp',
    transitionTimeMs: 5,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'L. Ramp',
    switchDownTimeMs: 1,
    switchIdToTrigger: 62,
    nextState: 'L. Ramp Exit',
    transitionTimeMs: 15,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'L. Ramp Exit',
    switchDownTimeMs: 1,
    nextState: 'Left  Inlane',
    transitionTimeMs: 2,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'R. Ramp Enter',
    switchDownTimeMs: 1,
    switchIdToTrigger: 63,
    nextState: 'R. Ramp',
    transitionTimeMs: 5,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'R. Ramp',
    switchDownTimeMs: 1,
    switchIdToTrigger: 64,
    nextState: 'R. Ramp Exit',
    transitionTimeMs: 15,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'R. Ramp Exit',
    switchDownTimeMs: 1,
    nextState: 'Right Inlane',
    transitionTimeMs: 2,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Left Lock',
    switchDownTimeMs: 1,
    switchIdToTrigger: 51,
    solenoidIdToLeaveState: 16,
    nextState: 'stFree',
    transitionTimeMs: 10 },
  { name: 'Skull Drop Target 2',
    switchDownTimeMs: 1,
    switchIdToTrigger: 77,
    nextState: 'stFree',
    transitionTimeMs: 1,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Ball Popper',
    switchDownTimeMs: 5,
    switchIdToTrigger: 76,
    solenoidIdToLeaveState: 1,
    nextState: 'Gun Loaded',
    transitionTimeMs: 5 },
  { name: 'Gun Loaded',
    switchDownTimeMs: 1,
    switchIdToTrigger: 31,
    solenoidIdToLeaveState: 2,
    nextState: 'Gun Fired',
    transitionTimeMs: 1 },
  { name: 'Orbit Target 1',
    switchDownTimeMs: 1,
    switchIdToTrigger: 71,
    nextState: 'stFree',
    transitionTimeMs: 1,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Orbit Target 2',
    switchDownTimeMs: 1,
    switchIdToTrigger: 72,
    nextState: 'stFree',
    transitionTimeMs: 1,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Orbit Target 3',
    switchDownTimeMs: 1,
    switchIdToTrigger: 73,
    nextState: 'stFree',
    transitionTimeMs: 1,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Orbit Target 4',
    switchDownTimeMs: 1,
    switchIdToTrigger: 74,
    nextState: 'stFree',
    transitionTimeMs: 1,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Orbit Target 5',
    switchDownTimeMs: 1,
    switchIdToTrigger: 75,
    nextState: 'stFree',
    transitionTimeMs: 1,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Left Rollover',
    switchDownTimeMs: 1,
    switchIdToTrigger: 56,
    nextState: 'Jet Bumper 1',
    transitionTimeMs: 10,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Jet Bumper 1',
    switchDownTimeMs: 1,
    switchIdToTrigger: 41,
    nextState: 'Jet Bumper 2',
    transitionTimeMs: 2,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Jet Bumper 2',
    switchDownTimeMs: 1,
    switchIdToTrigger: 42,
    nextState: 'Jet Bumper 3',
    transitionTimeMs: 2,
    options: [ 'INSTANT_LEAVE_STATE' ] },
  { name: 'Jet Bumper 3',
    switchDownTimeMs: 1,
    switchIdToTrigger: 43,
    nextState: 'stFree',
    transitionTimeMs: 3,
    options: [ 'INSTANT_LEAVE_STATE' ] }
];
