'use strict';

const STATEDEFINITION =
  `{stTrough4, stTrough3, stTrough2, stTrough1, stTrough, stDrain,
      stShooter, stBallLane, stRightOutlane, stLeftOutlane, stRightInlane, stLeftInlane, stLeftSling, stRightSling, stLeftJet, stRightJet, stBottomJet,
      stEnterLRamp, stLRampMade, stLHabitrail, stEnterRRamp, stRRampMade, stRHabitrail, stTower, stTowerLock,
      stLeftLoop1, stLeftLoop2, stRLoop2, stRLoop1, stRightLoop1, stRightLoop2, stLLoop2, stLLoop1, stLTopLane, stLJet, stRJet, stBJet, stRLoopExit, stRTopLane, stLLoopExit,
      stEject, stOutFromHole, stCatapult, stCatapultHole, stFired, stRBankTop, stRBankMid, stRBankBot,
      stLTroll, stLTroll2, stRTroll, stRTroll2, stLTrollTgt, stRTrollTgt,
      stLeftTopLane, stRightTopLane,
      stLeftPopper, stOutFromH, stLockLane, stLockHole, stCastle, stCastleMoat, stHitCastle, stHitCastle2, stHitCastle3, stEnterCastle, stEnterCastle2}`;

const SOLENOIDS = [
  '#define sLaunch		1',
  '#define sTrough		2',
  '#define sLeftPopper	3',
  '#define sCastle		4',
  '#define sCastleGateP	5',
  '#define sCastleGateH	6',
  '#define sKnocker	7',
  '#define sCatapult	8',
  '#define sRightEject	9',
  '#define sLeftSling	10',
  '#define sRightSling	11',
  '#define sLeftJet	12',
  '#define sBottomJet	13',
  '#define sRightJet	14',
  '#define sTowerDivP	15',
  '#define sTowerDivH	16',
  '#define sTowerLockPost	26',
  '#define sRightGate	27',
  '#define sLeftGate	28',
  '#define sLTrollP	33',
  '#define sLTrollH	34',
  '#define sRTrollP	35',
  '#define sRTrollH	36',
  '#define sDBMotor	41',
];

const SWITCHES = [
'  #define swLaunch	11',
'  #define swCatapultTgt	12',
'  #define swStart      	13',
'  #define swTilt       	14',
'  #define swLTrollTgt	15',
'  #define swLeftOutlane	16',
'  #define swRightInlane	17',
'  #define swShooter	18',
'  #define swSlamTilt	21',
'  #define swCoinDoor	22',
'  #define swTicket     	23',
'  #define swRTrollTgt	25',
'  #define swLeftInlane	26',
'  #define swRightOutlane	27',
'  #define swRightEject	28',
'  #define swTroughJam	31',
'  #define swTrough1	32',
'  #define swTrough2	33',
'  #define swTrough3	34',
'  #define swTrough4	35',
'  #define swLPopper	36',
'  #define swCastleGate	37',
'  #define swCatapult	38',
'  #define swEnterMoat	41',
'  #define swCastleLock	44',
'  #define swLTrollUPF	45',
'  #define swRTrollUPF	46',
'  #define swLeftTopLane	47',
'  #define swRightTopLane	48',
'  #define swLeftSling	51',
'  #define swRightSling	52',
'  #define swLeftJet	53',
'  #define swBottomJet	54',
'  #define swRightJet	55',
'  #define swDBUp		56',
'  #define swDBDown	57',
'  #define swTowerExit	58',
'  #define swEnterLRamp	61',
'  #define swLRampMade	62',
'  #define swEnterRRamp	63',
'  #define swRRampMade	64',
'  #define swLLoopLo	65',
'  #define swLLoopHi	66',
'  #define swRLoopLo	67',
'  #define swRLoopHi	68',
'  #define swRBankTop	71',
'  #define swRBankMid	72',
'  #define swRBankBot	73',
  '#define swLTrollUp	74',
  '#define swRTrollUp	75',
];

const STATE = [
'  {"Not Installed",	0,0,		 0,		stDrain,	0,	0,	0,	SIM_STNOTEXCL}',
'  {"Moving"}',
'  {"Playfield",		0,0,		 0,		0,		0,	0,	0,	SIM_STNOTEXCL}',

  /*Line 1*/
'  {"Trough 4",		1,swTrough4,	0,		stTrough3,	1}',
'  {"Trough 3",		1,swTrough3,	0,		stTrough2,	1}',
'  {"Trough 2",		1,swTrough2,	0,		stTrough1,	1}',
'  {"Trough 1",		1,swTrough1,	sTrough,	stTrough,	1}',
'  {"Trough Jam",	1,swTroughJam,  0,		stShooter,	1}',
'  {"Drain",		1,0,		0,		stTrough4,	0,	0,	0,	SIM_STNOTEXCL}',

  /*Line 2*/
'  {"Shooter",		1,swShooter,	 sLaunch,	stBallLane,	0,	0,	0,	SIM_STNOTEXCL|SIM_STSHOOT}',
'  {"Ball Lane",		1,0,		 0,		stLTopLane,	12,	0,	0,	SIM_STNOTEXCL}',
'  {"Right Outlane",	1,swRightOutlane,0,		stDrain,	15}',
'  {"Left Outlane",	1,swLeftOutlane, 0,		stDrain,	15}',
'  {"Right Inlane",	1,swRightInlane, 0,		stFree,		5}',
'  {"Left Inlane",	1,swLeftInlane,	 0,		stFree,		5}',
'  {"Left Slingshot",	1,swLeftSling,	 0,		stFree,		1}',
'  {"Rt Slingshot",	1,swRightSling,	 0,		stFree,		1}',
'  {"Left Bumper",	1,swLeftJet,	 0,		stFree,		1}',
'  {"Right Bumper",	1,swRightJet,	 0,		stFree,		1}',
'  {"Bottom Bumper",	1,swBottomJet,	 0,		stFree,		1}',

  /*Line 3*/
'  {"Enter L. Ramp",	1,swEnterLRamp,	 0,		stLRampMade,	7}',
'  {"L. Ramp Made",	1,swLRampMade,	 0,		stLHabitrail,	3}',
'  {"L. Habitrail",	1,0,		 0,		stLeftInlane,	7}',
'  {"Enter R. Ramp",	1,swEnterRRamp,	 0,		stRRampMade,	7, sTowerDivH, stTower}',
'  {"R. Ramp Made",	1,swRRampMade,	 0,		stRHabitrail,	3}',
'  {"R. Habitrail",	1,0,		 0,		stRightInlane,	5}',
'  {"Damsel Tower",	10,swTowerExit,	 0,		stTowerLock,	0}',
'  {"Damsel Tower 2",	1,0,	 	 0,		0,		0}',

  /*Line 4*/
'  {"Enter L. Loop",	1,swLLoopLo,	 0,		stLeftLoop2,	2}',
'  {"L. Loop Sw #2",	2,swLLoopHi,	 0,		stRTopLane,	4,sRightGate, stRLoop2}',
'  {"R. Loop Sw #2",	1,swRLoopHi,	 0,		stRLoop1,	2}',
'  {"R. Loop Sw #1",	1,swRLoopLo,	 0,		stFree,		3}',
'  {"Enter R. Loop",	1,swRLoopLo,	 0,		stRightLoop2,	2}',
'  {"R. Loop Sw #3",	2,swRLoopHi,	 0,		stLTopLane,	4,sLeftGate, stLLoop2}',
'  {"L. Loop Sw #3",	1,swLLoopHi,	 0,		stLLoop1,	2}',
'  {"L. Loop Sw #1",	1,swLLoopLo,	 0,		stFree,		3}',
'  {"Top Left Lane",	1,swLeftTopLane, 0,		stLJet,		5}',
'  {"Left Bumper 2",	1,swLeftJet,	 0,		stRJet,		3}',
'  {"Right Bumper 2",	1,swRightJet,	 0,		stBJet,		3}',
'  {"Bottom Bumper 2",	1,swBottomJet,	 0,		stRLoopExit,	5}',
'  {"Down F. Right",	1,swRLoopLo,	 0,		stFree,		5}',
'  {"Top Right Lane",	1,swRightTopLane,0,		stLJet,		5}',
'  {"Down From Left",	1,swLLoopLo,	 0,		stFree,		5}',

  /*Line 5*/
'  {"Merlin\'s Hole",	1,swRightEject,  sRightEject,	stOutFromHole,	0}',
'  {"Out From Hole",	1,0,		 0,		stRLoopExit,	5}',
'  {"Catapult Tgt.",	1,swCatapultTgt, 0,		stCatapultHole,	4}',
'  {"Catapult",		1,swCatapult,	 sCatapult,	stFired,	0}',
'  {"Ball Fired",	1,0,		 0,		stLRampMade,	3}',
'  {"R. Top Target",	1,swRBankTop,	 0,		stFree,		3}',
'  {"R. Mid Target",	1,swRBankMid,	 0,		stFree,		3}',
'  {"R. Bot Target",	1,swRBankBot,	 0,		stFree,		3}',

  /*Line 6*/
  '{"Left Troll",	0,0,		 0,		0,		0}',
  '{"Left Troll 2",	1,swLTrollUPF,	 0,		stFree,		5}',
  '{"Right Troll",	0,0,		 0,		0,		0}',
  '{"Right Troll 2",	1,swRTrollUPF,	 0,		stFree,		5}',
  '{"Left Troll T.",	1,swLTrollTgt,	 0,		stFree,		3}',
  '{"Right Troll T.",	1,swRTrollTgt,	 0,		stFree,		3}',

  /*Line 7*/
  '{"Top Left Lane 2",	1,swLeftTopLane, 0,		stFree,		3}',
  '{"Top Right Lane 2",	1,swRightTopLane,0,		stFree,		3}',

  /*Line 8*/
  '{"Left Hole",		1,swLPopper,	 sLeftPopper,	stOutFromH,	0}',
  '{"Out From Hole 2",	1,0,		 0,		stLLoopExit,	3}',
  '{"Lock Lane",		1,0,		 0,		stLockHole,	3}',
  '{"Castle Lock",	1,swCastleLock,	 0,		stLeftPopper,	7}',
  '{"",			0,0,		 0,		0,		0}',
  '{"Castle Moat",	1,swEnterMoat,	 0,		stLeftPopper,	7}',
  '{"Castle Hit",	1,swEnterMoat,   0,		stHitCastle2,	1}',
  '{"Castle Hit 2",	1,swCastleGate,	 0,		stHitCastle3,	1}',
  '{"Castle Hit 3",	1,swEnterMoat,	 0,		stFree,		4}',
  '{"Enter Castle",	1,swEnterMoat,	 0,		stEnterCastle2,	1}',
  '{"Enter Castle 2",	1,swCastleGate,  0,		stLockHole,	4}',
];

module.exports = {
  STATE,
  SWITCHES,
  SOLENOIDS,
  STATEDEFINITION,
};
